# Generated by Django 5.2.4 on 2025-07-03 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0002_studentproxymodel_user_batch_user_current_semester_and_more'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectivePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, default=1)),
                ('priority_text', models.CharField(blank=True, max_length=100, null=True)),
                ('desired_number_of_subjects', models.IntegerField(default=2)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.electivesession', verbose_name='Semester')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authuser.studentproxymodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.electivesubject')),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Priorities',
                'unique_together': {('subject', 'session', 'priority', 'student')},
            },
        ),
    ]
