# Generated by Django 4.2.7 on 2025-09-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivepriority',
            name='desired_number_of_subjects',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electivepriority',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
