# Generated by Django 4.2.7 on 2026-03-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivepriority',
            name='desired_number_of_subjects',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
