# Generated by Django 5.2.4 on 2025-07-07 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_electivesubject_max_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electivesubject',
            name='min_students',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Minimum number of students required'),
        ),
    ]
